"""
Gemma Swarm — Autonomous LinkedIn Drafter
==========================================
Runs on same schedule as researcher, immediately after.
Takes research synthesis as input, drafts 3 LinkedIn post suggestions per topic.
Each topic gets its own dated Google Doc and its own Slack notification.
1 LLM call per topic.
"""

import logging
import time
from datetime import datetime

logger = logging.getLogger(__name__)

SLEEP_BEFORE_CALL = 30


def run(
    research_results: list[dict],
    slack_client,
    autonomous_channel_id: str,
):
    """
    Generate LinkedIn post drafts from research results.
    research_results: list of {topic, synthesis, doc_link} from researcher.run()
    Each topic gets its own doc and Slack notification.
    """
    from autonomous.jobs.activity_logger import log

    if not research_results:
        logger.info("[linkedin_drafter] No research results — skipping.")
        return

    for i, result in enumerate(research_results):
        logger.info(f"[linkedin_drafter] Drafting posts for topic: {result['topic']}")
        _draft_for_topic(result, slack_client, autonomous_channel_id, log)

        # Sleep between topics to avoid hammering the LLM
        if i < len(research_results) - 1:
            logger.info(f"[linkedin_drafter] Sleeping {SLEEP_BEFORE_CALL}s before next topic...")
            time.sleep(SLEEP_BEFORE_CALL)


def _draft_for_topic(
    result: dict,
    slack_client,
    autonomous_channel_id: str,
    log,
):
    """Generate and post LinkedIn drafts for a single research topic."""
    from autonomous import pipeline_agent
    from tools.docs_api import docs_create_formatted

    topic     = result["topic"]
    synthesis = result["synthesis"]

    logger.info(f"[linkedin_drafter] Sleeping {SLEEP_BEFORE_CALL}s before LLM call...")
    time.sleep(SLEEP_BEFORE_CALL)

    # ── LLM: Generate drafts ───────────────────────────────────────────────────
    prompt = f"""You are a LinkedIn content writer. Based on the research summary below, write 3 LinkedIn post drafts.

Research topic: {topic}

Research content:
{synthesis[:6000]}

Rules for each draft:
- Under 200 words
- Professional but conversational tone
- Start with a hook (a bold statement, question, or surprising insight)
- End with a call to action or reflection question
- No hashtags unless they add genuine value
- Each draft should have a different angle or focus

Format your response EXACTLY like this — no extra text before or after:

DRAFT 1:
[post text here]

DRAFT 2:
[post text here]

DRAFT 3:
[post text here]"""

    response = pipeline_agent.ask(prompt)

    if not response or response.startswith("[LLM error"):
        logger.error(f"[linkedin_drafter] LLM call failed for topic: {topic}")
        log("linkedin_drafter", f"LinkedIn draft generation failed for: {topic}", "❌")
        return

    # ── Create formatted Google Doc ────────────────────────────────────────────
    date_str  = datetime.now().strftime("%Y-%m-%d")
    doc_title = f"LinkedIn Drafts — {topic} — {date_str}"
    doc_content = (
        f"## LinkedIn Post Drafts\n\n"
        f"Generated by Gemma Swarm Autonomous Pipeline\n"
        f"Topic: {topic}\n"
        f"Date: {date_str}\n\n"
        f"{response}"
    )

    try:
        doc  = docs_create_formatted(title=doc_title, content=doc_content)
        link = doc["link"]
        logger.info(f"[linkedin_drafter] Formatted doc created for '{topic}': {link}")
    except Exception as e:
        logger.error(f"[linkedin_drafter] Doc creation failed for '{topic}': {e}")
        log("linkedin_drafter", f"LinkedIn drafts doc creation failed for: {topic}", "❌")
        return

    try:
        slack_client.chat_postMessage(
            channel=autonomous_channel_id,
            text=(
                f"✍️ *LinkedIn post drafts ready*\n"
                f"Topic: *{topic}*\n"
                f"📄 <{link}|Open LinkedIn Drafts Doc — {date_str}>"
            ),
            mrkdwn=True,
        )
    except Exception as e:
        logger.error(f"[linkedin_drafter] Slack post failed for '{topic}': {e}")

    log("linkedin_drafter", f"LinkedIn drafts doc created for: {topic}", "✅")
