"""
Gemma Swarm — Autonomous LinkedIn Drafter
==========================================
Runs on same schedule as researcher, immediately after.
Takes research synthesis as input, drafts 3 LinkedIn post suggestions.
Saves them to a dated Google Doc.
Posts doc link to autonomous Slack channel.
1 LLM call total.
"""

import logging
import time
from datetime import datetime

logger = logging.getLogger(__name__)

SLEEP_BEFORE_CALL = 8  # seconds — respect rate limits after researcher's calls


def run(
    research_results: list[dict],
    slack_client,
    autonomous_channel_id: str,
):
    """
    Generate LinkedIn post drafts from research results.

    research_results: list of {topic, synthesis, doc_link} from researcher.run()
    """
    from autonomous.jobs.activity_logger import log
    from autonomous import pipeline_agent
    from tools.docs_api import docs_create

    if not research_results:
        logger.info("[linkedin_drafter] No research results — skipping.")
        return

    # Build combined input from all research topics
    combined_input = []
    for r in research_results:
        combined_input.append(
            f"### Topic: {r['topic']}\n\n{r['synthesis']}"
        )
    research_text = "\n\n---\n\n".join(combined_input)
    topics_str    = ", ".join(r["topic"] for r in research_results)

    # Sleep before LLM call to respect rate limits
    logger.info(f"[linkedin_drafter] Sleeping {SLEEP_BEFORE_CALL}s before LLM call...")
    time.sleep(SLEEP_BEFORE_CALL)

    # ── LLM: Generate drafts ───────────────────────────────────────────────────
    prompt = f"""You are a LinkedIn content writer. Based on the research summaries below, write 3 LinkedIn post drafts.

Research topics: {topics_str}

Research content:
{research_text[:6000]}

Rules for each draft:
- Under 200 words
- Professional but conversational tone
- Start with a hook (a bold statement, question, or surprising insight)
- End with a call to action or reflection question
- No hashtags unless they add genuine value
- Each draft should have a different angle or focus

Format your response EXACTLY like this — no extra text before or after:

DRAFT 1:
[post text here]

DRAFT 2:
[post text here]

DRAFT 3:
[post text here]"""

    response = pipeline_agent.ask(prompt)

    if not response or response.startswith("[LLM error"):
        logger.error("[linkedin_drafter] LLM call failed.")
        log("linkedin_drafter", "LinkedIn draft generation failed", "❌")
        return

    # ── Create Google Doc ──────────────────────────────────────────────────────
    date_str  = datetime.now().strftime("%Y-%m-%d")
    doc_title = f"LinkedIn Drafts — {date_str}"
    doc_content = (
        f"# {doc_title}\n\n"
        f"Generated by Gemma Swarm Autonomous Pipeline\n"
        f"Based on research: {topics_str}\n\n"
        f"---\n\n"
        f"{response}"
    )

    try:
        doc  = docs_create(title=doc_title, content=doc_content)
        link = doc["link"]
        logger.info(f"[linkedin_drafter] Doc created: {link}")
    except Exception as e:
        logger.error(f"[linkedin_drafter] Doc creation failed: {e}")
        log("linkedin_drafter", "LinkedIn drafts doc creation failed", "❌")
        return

    # ── Post to Slack ──────────────────────────────────────────────────────────
    try:
        slack_client.chat_postMessage(
            channel=autonomous_channel_id,
            text=(
                f"✍️ *LinkedIn post drafts ready*\n"
                f"Based on: {topics_str}\n"
                f"📄 <{link}|Open LinkedIn Drafts Doc — {date_str}>"
            ),
            mrkdwn=True,
        )
    except Exception as e:
        logger.error(f"[linkedin_drafter] Slack post failed: {e}")

    log("linkedin_drafter", f"LinkedIn drafts doc created for: {topics_str}", "✅")
